#version: '3.8'
#services:
#  smarthome:
#    build: .
#    container_name: smarthome
#    ports:
#      - "8888:8888"
version: '3'
services:
  smarthome:
    build: .
    container_name: smarthome
    ports:
      - "8888:8888"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - dsceltic_iot_oauthserver_default
    volumes:
      - /home/ubuntu/DsCeltic_IoT_GoogleHome/logs:/app/logs  # 호스트 경로를 컨테이너 경로에 매핑

networks:
  dsceltic_iot_oauthserver_default:
    external:
      name: dsceltic_iot_oauthserver_default