spring:
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://172.31.50.223:3306/ds_iot?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://3.37.23.88:3306/ds_iot?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: dsiotAppServer
    password: bZGPt9zQZ7aAtv+T]6}(*EfDONfO.R
server:
  port: 8888
mybatis:
  config-location: classpath:mybatis-config.xml

logging:
  file:
    path: /app/logs
  level:
    root: INFO  # 기본 로그 레벨을 INFO로 설정
    org.springframework: WARN  # Spring 관련 로그를 WARN으로 설정
    org.hibernate: ERROR  # Hibernate 관련 로그를 ERROR로 설정
    com.zaxxer.hikari: ERROR  # Hikari 관련 로그를 ERROR로 설정
    org.apache.ibatis: ERROR  # MyBatis 관련 로그를 ERROR로 설정

redis:
  host: ${SPRING_REDIS_HOST:localhost}
  port: ${SPRING_REDIS_PORT:6379}

custom:
  server:
    info:
      # Mobius에서 구독하는 AppServer 주소
      app_server_address: http://172.31.50.223:8080/GoogleToAppServer
      mobius_server_address: http://172.31.50.223:7579
      mobius_host: 172.31.50.223:7579
  google:
    oauth2:
      project_id: dsiot-52315
      client_id: 505891126739-acrkfeg05di1guvb6bpunj3cofb1lp41.apps.googleusercontent.com
      client_secret: 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
      #초단위(48시간)
      expires: 172800
      #초단위(24시간)
#      expires: 86400
