spring:
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.31.50.223:3306/dsiot?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: dsiotAppServer
    password: bZGPt9zQZ7aAtv+T]6}(*EfDONfO.R
server:
  port: 8888
mybatis:
  config-location: classpath:mybatis-config.xml

logging:
  level:
    com.zaxxer.hikari.HikariConfig: INFO
    com.zaxxer.hikari: TRACE
    root: info
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  file:
    path: logs
    name: app.log

redis:
  host: ${SPRING_REDIS_HOST:localhost}
  port: ${SPRING_REDIS_PORT:6379}

custom:
  server:
    info:
      # Mobius에서 구독하는 AppServer 주소
      app_server_address: http://172.31.50.223:8080/GoogleToAppServer
      mobius_server_address: http://172.31.50.223:7579
      mobius_host: 172.31.50.223:7579
  google:
    oauth2:
      project_id: dsiot-52315
      client_id: 505891126739-5nst99tq7ib748ovv80s6tdd5c0epcp3.apps.googleusercontent.com
      client_secret: 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
      #초단위(48시간)
      expires: 172800
      #초단위(24시간)
#      expires: 86400
